# Workflow Name
name: First Workflow

# Controls when the workflow will run
on: workflow_dispatch # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print welcome msg
        run: echo "Hello, world"
      - name: print goodbye msg
        run: |
            echo "First output",
            echo "Second output"
